import product1 from "../assets/images/shop/1.webp";
import product2 from "../assets/images/shop/2.webp";
import product3 from "../assets/images/shop/3.webp";
import product4 from "../assets/images/shop/4.webp";
import product5 from "../assets/images/shop/5.webp";
import product6 from "../assets/images/shop/6.webp";
import product7 from "../assets/images/shop/7.webp";
import product8 from "../assets/images/shop/8.webp";
export const allproducts = [
  {
    id: 1,
    title: "Powder Blush",
    brand: "Narse",
    slug: "narse-powder-blush",
    description: "Silky smooth powder blush with buildable color payoff.",
    price: 1200,
    image: product1,
    detailImages: [product1, product3, product5, product2],
    category: "Blush",
    rating: 5,
    quantity: 120,
  },
  {
    id: 2,
    title: "Liqued Blush",
    brand: "Narse",
    slug: "narse-liqued-blush",
    description: "Silky smooth powder blush with buildable color payoff.",
    price: 1800,
    image: product2,
    detailImages: [product2, product4, product6, product8],
    category: "Blush",
    rating: 5,
    quantity: 120,
  },
  {
    id: 3,
    title: "Matte Lipsticks",
    brand: "Medora",
    slug: "Matte-lipstick",
    description: "Silky smooth powder blush with buildable color payoff.",
    price: 500,
    image: product3,
    detailImages: [product1, product3, product5, product2],
    category: "lipstics",
    rating: 5,
    quantity: 120,
  },
  {
    id: 4,
    title: "Shine Lipsticks",
    brand: "Medora",
    slug: "shine-lipstick",
    description: "Silky smooth powder blush with buildable color payoff.",
    price: 500,
    image: product4,
    detailImages: [product8, product6, product4, product2],
    category: "lipstics",
    rating: 5,
    quantity: 120,
  },
  {
    id: 5,
    title: "Revolution Eyeshadow Pallet",
    brand: "Revolution",
    slug: "Revolution-Eyeshadow-Pallet",
    description: "Silky smooth powder blush with buildable color payoff.",
    price: 2500,
    image: product5,
    detailImages: [product7, 5, product3, product1],
    category: "pallets",
    rating: 5,
    quantity: 120,
  },
  {
    id: 6,
    title: "Missrose Glowing Eyeshadow Pallet",
    brand: "Missrose",
    slug: "Missrose-Eyeshadow-Pallet",
    description: "Silky smooth powder blush with buildable color payoff.",
    price: 3000,
    image: product6,
    detailImages: [product1, product3, product5, product7],
    category: "pallets",
    rating: 5,
    quantity: 120,
  },
  {
    id: 7,
    title: "Emelie Makeup brush set",
    brand: "Emelie",
    slug: "Emelie-makeup-brush-set",
    description: "Silky smooth powder blush with buildable color payoff.",
    price: 2500,
    image: product7,
    detailImages: [product8, product6, product4, product2],
    category: "brushes",
    rating: 5,
    quantity: 120,
  },
  {
    id: 8,
    title: "Zoeva brush set ",
    brand: "Zoeva",
    slug: "Zoeva-brush-set",
    description: "Silky smooth powder blush with buildable color payoff.",
    price: 2700,
    image: product8,
    detailImages: [product3, product6, product8, product1],
    category: "brushes",
    rating: 5,
    quantity: 120,
  },
  {
    id: 9,
    title: "Tarte Foundation",
    brand: "Tarte",
    slug: "Tarte-Foundation",
    description: "Silky smooth powder blush with buildable color payoff.",
    price: 4000,
    image: product1,
    detailImages: [product1, product3, product5, product7],
    category: "foundations",
    rating: 5,
    quantity: 120,
  },
  {
    id: 10,
    title: "Huda Beauty Foundation",
    brand: "Tarte",
    slug: "HudaBeauty-Foundation",
    description: "Silky smooth powder blush with buildable color payoff.",
    price: 5000,
    image: product2,
    detailImages: [product3, product6, product8, product1],
    category: "foundations",
    rating: 5,
    quantity: 120,
  },
  {
    id: 11,
    title: "Narse Beauty Foundation",
    brand: "Narse",
    slug: "Narse-Foundation",
    description: "Silky smooth powder blush with buildable color payoff.",
    price: 2700,
    image: product3,
    detailImages: [product1, product3, product5, product2],
    category: "foundations",
    rating: 5,
    quantity: 120,
  },
  {
    id: 12,
    title: "MAC Beauty Foundation",
    brand: "MAC",
    slug: "Mac-Foundation",
    description: "Silky smooth powder blush with buildable color payoff.",
    price: 2500,
    image: product4,
    detailImages: [product1, product3, product5, product2],
    category: "foundations",
    rating: 5,
    quantity: 120,
  },
  {
    id: 13,
    title: "ELFE Beauty Foundation",
    brand: "ElFE",
    slug: "Elfe-Foundation",
    description: "Silky smooth powder blush with buildable color payoff.",
    price: 5000,
    image: product5,
    detailImages: [product3, product6, product8, product1],
    category: "foundations",
    rating: 5,
    quantity: 120,
  },
  {
    id: 14,
    title: "Maybelline Mascara",
    brand: "Maybelline",
    slug: "Maybelline-Mascara",
    description: "Silky smooth powder blush with buildable color payoff.",
    price: 1000,
    image: product6,
    detailImages: [product1, product3, product5, product2],
    category: "Mascara",
    rating: 1,
    quantity: 120,
  },

  {
    id: 15,
    title: "Essence Mascara",
    brand: "Essence",
    slug: "Essence-Mascara",
    description: "Silky smooth powder blush with buildable color payoff.",
    price: 1500,
    image: product7,
    detailImages: [product3, product6, product8, product1],
    category: "Mascara",
    rating: 2,
    quantity: 120,
  },
  {
    id: 16,
    title: "Dior Mascara",
    brand: "Dior",
    slug: "Dior-Mascara",
    description: "Silky smooth powder blush with buildable color payoff.",
    price: 1800,
    image: product8,
    detailImages: [product1, product3, product5, product2],
    category: "Mascara",
    rating: 5,
    quantity: 120,
  },
  {
    id: 17,
    title: "Dior Mascara",
    brand: "Dior",
    slug: "Dior-Mascara",
    description: "Silky smooth powder blush with buildable color payoff.",
    price: 1800,
    image: product1,
    detailImages: [product3, product6, product8, product1],
    category: "Mascara",
    rating: 5,
    quantity: 120,
  },
  {
    id: 18,
    title: "MAC Highlighter",
    brand: "MAC",
    slug: "MAC-Highlighter",
    description: "Silky smooth powder blush with buildable color payoff.",
    price: 2000,
    image: product2,
    detailImages: [product1, product3, product5, product2],
    category: "Highlighter",
    rating: 3,
    quantity: 120,
  },

  {
    id: 19,
    title: "NARS Highlighter",
    brand: "NARS",
    slug: "NARS-Highlighter",
    description: "Silky smooth powder blush with buildable color payoff.",
    price: 2500,
    image: product3,
    detailImages: [product1, product3, product5, product2],
    category: "Highlighter",
    rating: 5,
    quantity: 120,
  },
  {
    id: 20,
    title: "Makeup City Blander",
    brand: "Makeup City",
    slug: "Makeup-City-Blander",
    description: "Silky smooth powder blush with buildable color payoff.",
    price: 2500,
    image: product4,
    detailImages: [product3, product6, product8, product1],
    category: "Blanders",
    rating: 4,
    quantity: 120,
  },
];
